version: '3'
services:
  application:
    build: .
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application